---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ttyd-k9s-rolebinding
  labels:
    app.kubernetes.io/name: k9s
roleRef:
  kind: ClusterRole
  name: ttyd-k9s-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ttyd-k9s-sa
    namespace: ttyd-k9s
